#!/bin/bash
mkdir ~/.jupyter
cp ./.binder/jupyter_notebook_config.py ~/.jupyter/
pip install -r requirements-ci.txt
pip install setuptools wheel Cython numpy==1.26.0
pip install --no-build-isolation -e .