
title: OpenScope Databook
author: Carter Peene
logo: ../data/images/logo.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    language: en
  sphinx:
    html_context:
      default_mode: dark
  extra_extensions:
    - insert_authors_version
    - sphinx.ext.intersphinx

repository:
  url: https://github.com/AllenInstitute/openscope_databook
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-TJPN1M4PDX

launch_buttons:
  notebook_interface: "classic"
  jupyterhub_url: "https://hub.dandiarchive.org"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true
