
title: OpenScope Databook
author: Carter Peene
logo: ../data/images/logo.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/AllenInstitute/openscope_databook
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: "https://hub.dandiarchive.org"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"
