
name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on:
      group: LargerInstance

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
      TESTING: True

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: Installing package
        run: pip install -e .

      - name: Installing build dependencies
        run: |
          pip install markupsafe==2.0.1
          pip install jupyter
          pip install -U jupyter-book
          pip install nbmake
          pip install pytest-xdist
        
      - name: Printing environment
        run: pip freeze

      - name: Testing Basics Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=100000 -n=auto "./docs/basics"
          rm ./docs/basics/*.nwb
        
      - name: Testing Visualization Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/visualization"
          rm ./docs/visualization/*.nwb

      - name: Testing First-Order Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/first-order"
          rm ./docs/first-order/*.nwb
        
      - name: Testing Higher-Order Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/higher-order"
          rm ./docs/higher-order/*.nwb

      - name: Testing Project Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/projects"
          rm ./docs/projects/*.nwb
        
      - name: Testing Embargoed Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/embargoed"
          rm ./docs/embargoed/*.nwb        

      - name: Printing log
        run: git status
      
      - name: Printing shortlog
        run: git log | git shortlog -sn  

      - name: Build Jupyter book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs
