
name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: print environment
        run: pip freeze

      - name: Installing requirements
        run: pip install -r requirements.txt --user

      - name: Installing build dependencies
        run: pip install markupsafe==2.0.1

      - name: Installing Jupyter book
        run: pip install -U jupyter-book

      - name: Build Jupyter book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs
