
name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" , "dev"]

  workflow_dispatch:

jobs:
  build:
    runs-on:
      group: LargerInstance
    container: 
      image: rcpeene/openscope_databook:latest

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
      TESTING: True

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install Python build headers
        run: |
          apt-get update
          apt-get install -y python3-dev g++

      - name: Install Python environment
        run: |
          python3 -m pip install --upgrade pip setuptools wheel Cython numpy==1.26.0
          python3 -m pip install --upgrade --upgrade-strategy eager -r requirements-ci.txt
          python3 -m pip install --no-deps --no-build-isolation -e .
          python3 -m pip install -U jupyter-book==1.0.0
        
      - name: Printing environment
        run: python3 -m pip freeze

      - name: Testing Embargoed Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/embargoed"
          rm ./docs/embargoed/*.nwb

      - name: Testing Higher-Order Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/higher-order" --ignore docs/higher-order/behavioral_state.ipynb
          rm ./docs/higher-order/*.nwb

      - name: Testing Basics Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=100000 -n=auto "./docs/basics"
          rm ./docs/basics/*.nwb
        
      - name: Testing Visualization Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/visualization"
          rm ./docs/visualization/*.nwb

      - name: Testing First-Order Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/first-order"
          rm ./docs/first-order/*.nwb
        
      - name: Testing Project Notebooks
        run: |
          pytest --nbmake --nbmake-timeout=8000 -n=auto "./docs/projects"
          rm ./docs/projects/*.nwb
        
      - name: Printing log
        run: |
          git config --global --add safe.directory /__w/openscope_databook/openscope_databook
          git status
      
      - name: Printing shortlog
        run: git log | git shortlog -sn  

      - name: Build Jupyter book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs
