
name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: Installing package
        run: pip install -e .

      - name: Installing requirements
        run: pip install -r ./requirements.txt

      - name: Installing build dependencies
        run: |
          pip install markupsafe==2.0.1
          pip install jupyter
          pip install -U jupyter-book
          pip install nbmake
          pip install pytest-xdist
        
      - name: Printing environment
        run: pip freeze

      - name: Testing notebooks
        run: pytest --nbmake --nbmake-timeout=5000 -n=auto "./docs"
        
      - name: Build Jupyter book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs
