name: deployment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Show Python and pip versions
        run: |
          python --version
          python -m pip --version

      - name: Uninstall setuptools fully
        run: |
          python -m pip uninstall -y setuptools

      - name: Clean install build tools
        run: |
          python -m pip install --upgrade --force-reinstall --no-cache-dir setuptools wheel build setuptools_scm

      - name: Install git dependencies explicitly
        run: |
          python -m pip install --upgrade --force-reinstall git+https://github.com/sytseng/ndx-harvey-swac
          python -m pip install --upgrade --force-reinstall git+https://github.com/AllenInstitute/ophys_nway_matching.git

      - name: Build wheel explicitly without isolation
        run: |
          python -m pip install --upgrade build
          python -m build --wheel --no-isolation .

      - name: Install your package editable
        run: python -m pip install -e .

      - name: Install Jupyter Book
        run: python -m pip install -U jupyter-book

      - name: Build Jupyter Book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
