
name: deployment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Installing python
        run: |
          sudo apt-get update
          sudo apt install python3.12
          sudo apt-get install build-essential

      - name: Upgrading pip
        run: pip install --upgrade pip
        
      - name: Installing dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install markupsafe==2.0.1 numpy cython --no-cache-dir

      - name: Installing package
        run: pip install -e .

      - name: Installing Jupyter book
        run: pip install -U jupyter-book

      - name: Printing log
        run: git status
      
      - name: Printing shortlog
        run: git log | git shortlog -sn  

      - name: Build Jupyter book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs
            
      - name: Deploy book to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

