
name: deployment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check python and pip versions
        run: |
          python --version
          python -m pip --version
          python -m pip list

      - name: Upgrade build tools
        run: python -m pip install --upgrade pip setuptools wheel build setuptools_scm

      - name: Installing package
        run: python -m pip install -e .

      - name: Installing Jupyter book
        run: pip install -U jupyter-book

      - name: Printing log
        run: git status
      
      - name: Printing shortlog
        run: git log | git shortlog -sn  

      - name: Build Jupyter book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs
            
      - name: Deploy book to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

