name: deploy-book
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on:
      group: LargerInstance
    container:
      image: rcpeene/openscope_databook:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Install your package
        run: pip install -e .

      - name: Install build requirements
        run: |
          pip install -r requirements.txt
          pip install markupsafe==2.0.1
          pip install -U jupyter-book

      - name: Build Jupyter Book
        run: |
          jupyter-book clean ./docs
          jupyter-book build ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
