name: secret scan
on: push

jobs:
  secret_scan:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Getting changed files
        id: changed_files
        uses: Ana06/get-changed-files@v2.2.0
        
      - name: Get file contents
        id: file_contents
        run: echo "contents=$(cat ${{ steps.changed_files.outputs.added_modified }})" >> $GITHUB_OUTPUT

      - name: Check for secrets
        env:
          DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
        if: contains( ${{ steps.file_contents.outputs.contents }}, $DANDI_API_KEY )
        run: exit 1
