name: test
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: 
      group: LargerInstance
    container:
      image: rcpeene/openscope_databook:latest

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
      TESTING: True

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'

      # - name: Upgrading pip
      #   run: pip install --upgrade pip

      - name: Installing requirements
        run: pip install -r ./requirements.txt

      - name: Installing packages again (this prevents a weird error in cell matching nb)
        run: pip install -r requirements.txt

      - name: Installing build dependencies
        run: |
          pip install markupsafe==2.0.1
          pip install jupyter
          pip install -U jupyter-book
          pip install nbmake
          pip install pytest-xdist

      - name: Printing environment
        run: pip freeze
      
      - name: Getting changed files
        id: changed_files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          filter: "*.ipynb"
        
      - name: Testing notebooks
        if: ${{ steps.changed_files.outputs.added_modified  != '' }}
        run: pytest --nbmake --nbmake-timeout=5000 -n=auto ${{ steps.changed_files.outputs.added_modified }}

