name: test
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: print environment
        run: pip freeze

      - name: Installing requirements
        run: pip install -r .binder/requirements.txt --user

      - name: Installing build dependencies
        run: |
          pip install markupsafe==2.0.1
          pip install jupyter
          pip install -U jupyter-book
          pip install nbmake
          pip install pytest-xdist
      
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: nrwl/nx-set-shas@v3
        id: last_successful_commit_push
        with:
          main-branch-name: ${{ steps.branch-name.outputs.current_branch }} # Get the last successful commit for the current branch.
          workflow-id: 'test.yml'
      
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v35
        with:
          base_sha: ${{ steps.last_successful_commit_push.outputs.base }}
          files: |
            *.ipynb

      - name: Print changed files
        run: echo "${{ steps.changed_files.outputs.all_changed_files }}"

      - name: Testing notebooks
        run: pytest --nbmake --nbmake-timeout=5000 ${{ steps.changed_files.outputs.all_changed_files }}
