name: test
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: 
      group: LargerInstance
    container:
      image: rcpeene/openscope_databook:latest

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
      TESTING: True

    steps:
      - uses: actions/checkout@v3

      - name: Install Python build headers
        run: |
          apt-get update
          apt-get install -y python3-dev g++

      - name: Install build backend tools
        run: python3 -m pip install setuptools wheel Cython numpy==1.26.0

      # - name: Upgrading pip
      #   run: pip install --upgrade pip

      - name: Installing requirements
        run: python3 -m pip install -r ./requirements-ci.txt

      - name: Installing packages again (this prevents a weird error in cell matching nb)
        run: python3 -m pip install -r requirements-ci.txt

      - name: Installing build dependencies
        run: |
          python3 -m pip install markupsafe==2.0.1
          python3 -m pip install jupyter
          python3 -m pip install -U jupyter-book
          python3 -m pip install nbmake
          python3 -m pip install pytest-xdist

      - name: Printing environment
        run: python3 -m pip freeze
      
      - name: Getting changed files
        id: changed_files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          filter: "*.ipynb"
        
      - name: Testing notebooks
        if: ${{ steps.changed_files.outputs.added_modified  != '' }}
        run: pytest --nbmake --nbmake-timeout=5000 -n=2 ${{ steps.changed_files.outputs.added_modified }}

