name: test
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: 
      group: LargerInstance

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
      TESTING: True

    steps:
      - uses: actions/checkout@v3

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: print environment
        run: pip freeze

      - name: Install cython
        run: pip install cython numpy

      - name: Installing package
        run: pip install -e .

      - name: Installing requirements
        run: pip install -r ./requirements.txt

      - name: Installing build dependencies
        run: |
          pip install markupsafe==2.0.1
          pip install jupyter
          pip install -U jupyter-book
          pip install nbmake
          pip install pytest-xdist

      - name: Printing environment
        run: pip freeze
      
      - name: Getting changed files
        id: changed_files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          filter: "*.ipynb"
        
      - name: Testing notebooks
        if: ${{ steps.changed_files.outputs.added_modified  != '' }}
        run: pytest --nbmake-timeout=5000 -n=auto ${{ steps.changed_files.outputs.added_modified }}

