name: test
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: print environment
        run: pip freeze

      - name: Installing requirements
        run: pip install -r .binder/requirements.txt --user

      - name: Installing build dependencies
        run: |
          pip install markupsafe==2.0.1
          pip install jupyter
          pip install -U jupyter-book
          pip install nbmake
          pip install pytest-xdist
      
      - name: Getting changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
        
      - name: Extracting notebooks to test
        run: |
          filenames=()
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "${changed_file}."
            if [[ "${changed_file}" == *".ipynb" ]]; then
              filenames+=(${changed_file})
            fi
          done
          echo {$filenames}

      - name: Testing notebooks
        run: |
          if [[ ${#filenames[@]} -gt 0 ]]; then
            pytest --nbmake --nbmake-timeout=5000 $filenames
          fi

